services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minicon-dev
    volumes:
      - .:/app
    privileged: true
    stdin_open: true
    tty: true
    command: bash
